<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>afterThrowing Unit Tests</title>
	<script type="text/javascript" src="util/doh/runner.js"></script>
	<script type="text/javascript" src="../aop.js"></script>
	<script type="text/javascript">
		(function(global, doh, aop, undef) {

			var arg = "foo"; // const

			// Test fixture			
			function Fixture() {
				this.val = 0;
			}
			
			Fixture.prototype = {
				method: function(a) {
					this.val++;
					throw new Error('testing afterThrowing');
				}
			};
			
			doh.register('afterThrowing', [
				function testAfterReturning1() {
					var target = new Fixture();
					
					// Starting value
					doh.assertEqual(0, target.val);
					
					aop.afterThrowing(target, 'method', function afterReturning1(a) {
						// this should be the advised object
						doh.assertEqual(target, this);

						// arg should be the exception that was thrown
						doh.assertTrue(a instanceof Error);
						
						// after function should be called (duh) after
						// the original, so val will have changed.
						doh.assertEqual(1, this.val);
					});
					
					try {
						target.method(arg);
						doh.assertTrue(false);
					} catch(e) {}
					
					// after method call, val should have changed
					doh.assertEqual(1, target.val);
				},
				function testAfterReturning2() {
					var target = new Fixture();
					var count = 0;
					
					// Add 3 advices and test their invocation order,
					// args, and return value

					// Starting value
					doh.assertEqual(0, target.val);
				
					aop.afterThrowing(target, 'method', function afterReturning0(a) {
						// this should be the advised object
						doh.assertEqual(target, this);

						// arg should be the exception that was thrown
						doh.assertTrue(a instanceof Error);
												
						// after function should be called (duh) after
						// the original, so val will have changed.
						doh.assertEqual(1, this.val);
				
						// after* advice is stacked left to right such that advice added
						// later is called later, so count should not have
						// been incremented yet.
						doh.assertEqual(0, count);

						// Increment count so it can be verified in next advice
						count++;
					});
					
					aop.afterThrowing(target, 'method', function afterReturning1(a) {
						// this should be the advised object
						doh.assertEqual(target, this);

						// arg should be the exception that was thrown
						doh.assertTrue(a instanceof Error);						
						
						// after function should be called (duh) after
						// the original, so val will have changed.
						doh.assertEqual(1, this.val);
				
						doh.assertEqual(1, count);
						
						// Increment count so it can be verified in next advice
						count++;
					});
				
					aop.afterThrowing(target, 'method', function afterReturning2(a) {
						// this should be the advised object
						doh.assertEqual(target, this);

						// arg should be the exception that was thrown
						doh.assertTrue(a instanceof Error);
						
						// after function should be called (duh) after
						// the original, so val will have changed.
						doh.assertEqual(1, this.val);

						doh.assertEqual(2, count);						
					});
					
					try {
						target.method(arg);
						doh.assertTrue(false);
					} catch(e) {}
					
					// after method call, val should have changed
					doh.assertEqual(1, target.val);
				}
			]);

			doh.run();
			
		})(window, doh, aop);
	</script>
</head>
<body>
	
</body>
</html>